task:

	@ echo "Backup your directory.";\
	echo "";\
	echo "Enter the source directory :";	read argument1;\
	echo "Enter the destination directory:";	read argument2;\
	echo "Enter the backup frequency (in seconds):";	read argument3;\
	echo "Enter the maximum number of backups:";	read argument4;\
	./backup.sh $$argument1 $$argument2 $$argument3 $$argument4;
